name: CI/CD

on:
    push:
        branches:
            - main
    pull_request: {}

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download deps
              uses: bahmutov/npm-install@v1

            - name: Lint
              run: yarn lint

    typecheck:
        name: Type check
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download deps
              uses: bahmutov/npm-install@v1

            - name: Type check
              run: yarn typecheck

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download deps
              uses: bahmutov/npm-install@v1

            - name: Jest
              run: yarn test

    e2e:
        name: E2E
        runs-on: ubuntu-latest
        needs: [lint, typecheck, test]
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download deps
              uses: bahmutov/npm-install@v1

            - name: Cypress
              uses: cypress-io/github-action@v4
              with:
                  build: yarn build
                  start: yarn start
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [lint, typecheck, test, e2e]
        if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push' }}
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download deps
              uses: bahmutov/npm-install@v1

            - name: Build
              run: yarn build

            - name: Deploy to production
              id: production
              uses: amondnet/vercel-action@v25
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
                  working-directory: ./build
                  vercel-args: '--prod'
                  alias-domains: |
                      getprimo.now.sh

    lighthouse:
        name: Lighthouse
        runs-on: ubuntu-latest
        needs: [deploy]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Run Lighthouse
              uses: treosh/lighthouse-ci-action@v9
              with:
                  urls: ${{ steps.production.outputs.preview-url }}
                  temporaryPublicStorage: true
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
