name: Format

on:
    push:
        branches:
            - main

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: pnpm

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.18.3

            - name: Install deps
              run: pnpm install --frozen-lockfile

            - name: Run format
              run: pnpm format

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_options: '--no-verify'
                  commit_message: Format
